<a href="https://colab.research.google.com/github/MalwareX95/Pytorch---Deep-learning-w-Python/blob/main/pytorchbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x * y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2, 5])

In [4]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand([2, 5])

In [7]:
y

tensor([[0.7662, 0.2578, 0.1472, 0.1042, 0.3929],
        [0.6102, 0.7158, 0.5953, 0.6156, 0.7138]])

In [8]:
y.view([1, 10])

tensor([[0.7662, 0.2578, 0.1472, 0.1042, 0.3929, 0.6102, 0.7158, 0.5953, 0.6156,
         0.7138]])

In [9]:
y

tensor([[0.7662, 0.2578, 0.1472, 0.1042, 0.3929],
        [0.6102, 0.7158, 0.5953, 0.6156, 0.7138]])

In [10]:
y = y.view([1, 10])

In [11]:
y

tensor([[0.7662, 0.2578, 0.1472, 0.1042, 0.3929, 0.6102, 0.7158, 0.5953, 0.6156,
         0.7138]])